In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('AviationData.csv', encoding='latin-1')
df.head()

/home/zakidev/anaconda3/envs/learn-env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (6,7,28) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50249 non-null  object
 9   Airport.Name            52790 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87572 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81812 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82508 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

In [5]:
df.isna().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38640
Airport.Name              36099
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1317
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7077
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6381
Publication.Date          13771
dtype: int64

In [6]:
list(df['Model'])

['108-3',
 'PA24-180',
 '172M',
 '112',
 '501',
 'DC9',
 '180',
 '140',
 '401B',
 'NAVION L-17B',
 'PA-28-161',
 'V35B',
 '17-30A',
 'R172K',
 'A',
 '19',
 '280C',
 '180',
 '172',
 'WCS-222 (BELL 47G)',
 '152',
 '150L',
 '206L-1',
 'PA-24-180',
 'AA-5B',
 '414A',
 'BE-58',
 'M-5-235C',
 '210L',
 '7GCBC',
 '182',
 'AT-301',
 'PA-28-161',
 'PA-34-200T',
 'T337G',
 'PA-28R-200',
 '206',
 'A',
 'PA-22',
 'PA-31',
 '114',
 'PA-24-250',
 'PA-28R-200',
 'TR182',
 'A185F',
 '340',
 'SA-316B',
 '35',
 '152',
 'M-20J',
 'A75',
 '210',
 'V35',
 'C46',
 '172M',
 'PA-28-140',
 'TU206G',
 '152',
 'PA-24-250',
 '152',
 '172N',
 '152',
 'ASW 20',
 'P210N',
 '172',
 'PA-34',
 '305 (L-19)',
 '182A',
 'PA-23-250',
 '172N',
 '23-250',
 'M20G',
 'TU206F',
 '1',
 'U206',
 'PA-28-140',
 '210N',
 '180',
 '310L',
 'L-1011',
 'EMB-110P1',
 '414',
 'P35',
 'AA5B',
 '737-222',
 'PA-28R-201T',
 'A23-24',
 'PA-31-350',
 'T210N',
 '310',
 '172',
 '269C',
 '140',
 'SA 226-TC',
 'C-45H',
 'DHC-2-MK3',
 '206L-1',
 '150M',
 '150M',
 'BD-5B',
 '182P',
 '440',
 'PA-31',
 'PA-31T',
 'F50',
 '150',
 '180E',
 '170B',
 '206B',
 'C23',
 '172M',
 'PA-28-180',
 '180K',
 '210L',
 'M20F',
 'G35',
 '177B',
 'AA5A',
 'SA226-T(B)',
 'DHC-6-300',
 'AEROSTAR 601P',
 '152',
 '182P',
 '177RG',
 'QUICK SILVER',
 '182E',
 '150H',
 '340A',
 'PA-38-112',
 'CL-44D4',
 'PA-32',
 'PA-31-350',
 '58',
 '182N',
 'PA-23-250',
 '210',
 '152',
 '269C',
 'P210N',
 '402A',
 'DC-3',
 'PA-23-250',
 'PA-28-235',
 'AA-1',
 'PA-32',
 '207',
 'M-20',
 '301',
 'II',
 'FALCON 20',
 '172M',
 'S-58J',
 '172',
 'M20C',
 'G-164A',
 'DC-10-30',
 'A23A',
 'PA-32-300',
 '150M',
 'PA-34-200T',
 'PA-28-235',
 '150H',
 '206 L-1',
 '47G-2',
 'PA-38-112',
 'C-402B',
 '172',
 '172',
 '172RG',
 '177',
 '182M',
 '152II',
 'A188B',
 'PA-28-140',
 '172N',
 '152',
 '7GCBC',
 '369D',
 'UH1B',
 '152',
 '152',
 '172N',
 '7BCM',
 'PA-38-112',
 '28-151',
 '340A',
 '172H',
 'M20C',
 'A185F',
 'PA-32-260',
 '172N',
 'B200',
 '150',
 '172',
 'PA-28R-201T',
 'M20J',
 'TR182',
 '7AC',
 '177B',
 '172',
 '140',
 '172',
 '182L',
 '172N',
 '172P',
 'PA-22',
 '150L',
 '36',
 '152',
 'PA-28-161',
 '180K',
 '152',
 '152',
 'PA-22',
 '99',
 '172',
 'SA-360C',
 '182',
 '7ECA',
 'TR182',
 'P206',
 '1159',
 'PA-32',
 'PA-23-250',
 '150G',
 'U206G',
 'T210N',
 'BK-1',
 'M20J',
 'MU2B-40',
 'DC-10-10',
 '150J',
 'F19',
 '206L-1',
 'AEROSTAR 600',
 'R-22',
 '7KCAB',
 '206L-1',
 'PA-28',
 'PA-32R-300',
 'PA-28-140',
 'T210L',
 'A75N1',
 'PA-31',
 '7KCAB',
 'BC12-D',
 'PA-28-140',
 'S-55A',
 '180',
 '152',
 'PA-28-181',
 '415-C',
 '182H',
 '150',
 'PA-24-180',
 '182B',
 'PA-28-140',
 'P210N',
 '112TCA',
 'PA-28-180',
 '7KCAB',
 '172N',
 '152',
 'PA-38',
 '177RG',
 '172',
 '152',
 '172',
 '172N',
 'C-172',
 'PA-18A-150',
 '152',
 'PA-28R-201',
 'PA-28-161',
 '182P',
 '140',
 'C-23',
 'PA-38-112',
 'V35A',
 '200',
 '310R',
 '172',
 '402B',
 '185',
 '310',
 '95-C55',
 '172K',
 '421B',
 '401',
 'UH-19B',
 '421',
 'G-164B',
 '152',
 'PA-60-602P',
 'DHC-6-100',
 'PA-24-250',
 '500',
 '152',
 '172K',
 'PA-34',
 '112A',
 'J35',
 '150',
 '152',
 '7AC',
 '172',
 'PA-18',
 '150',
 '7EC',
 '214B-1',
 '150',
 '152',
 '17-30A',
 '150',
 'PA-28-140',
 'PA-38-112',
 'PA-28-161',
 '172N',
 'CP-65',
 'PA-28-161',
 'B737-2H4',
 '310D',
 'PA-23',
 'M20J',
 'PA-28-151',
 '152',
 'PA-28-151',
 '152(II)',
 '35',
 'PA-28R-180',
 '150M',
 '8GCBC',
 'PA-31-310',
 '172',
 'PA-31T2',
 '90',
 'YS-11A',
 '152',
 '172M',
 'PA-28RT-201T',
 '7ECA',
 '177RG',
 '210',
 '210',
 '727-235',
 'PA-23',
 'EMB-11OP1',
 'A36',
 'PA-28-140',
 'T210N',
 '2T1A-2',
 'B-727-200',
 'PA-44-180T',
 'FIREFLY',
 nan,
 '172H',
 '180',
 '172A',
 '58',
 'P206B',
 '47G2',
 '404',
 '51',
 '172L',
 '182Q',
 'PA-36-375',
 'PA-28-161',
 '152',
 '172N',
 '150M',
 '140',
 '56TC',
 '150',
 'G-21A',
 'PA-22-150',
 'PA-28-181',
 'PA-28-180',
 'DHC-6',
 'AA-5A',
 'PA-32R-301T',
 '152',
 '172N',
 'M-20C',
 '7GCBC',
 'PA-28-140',
 '152',
 '227C',
 '8KCAB',
 'HH-43F',
 '14-19-3A',
 '421C',
 'G-164A',
 'A185F',
 '180',
 'PA-38-112',
 '210A',
 'PA-60',
 'A188B',
 '206B',
 'PA-60/601P',
 '172',
 '152II',
 '210',
 'COMMANDER 114',
 'BE-95-C55',
 '150',
 '172',
 'SA-227',
 '201C',
 '310Q',
 '414',
 'DW-1',
 '210L',
 'PA-28-181',
 '421B',
 '23',
 'PA-23',
 'D18S',
 'R22',
 'B90',
 '152',
 '150',
 'PA-20',
 '182C',
 '152',
 '11AC',
 'T-34B',
 '150G',
 'PA-38-112',
 '170',
 '269C',
 '320C',
 'T210M',
 'FIREFLY-7',
 '152',
 'T21OL',
 'BALLOON AX7',
 'PA-32-260',
 '172N',
 '172L',
 'SGS1-260',
 'J3-F65',
 '140A',
 nan,
 '152',
 '47G',
 'PA-25-235',
 'PDQ-2',
 'PA-28-161',
 'PA-25-235C',
 '8GCBC',
 'PA-38-112',
 '206B III',
 'U206',
 'A152',
 '415-C',
 '500',
 '182RG',
 '35-B33',
 'J3F-65',
 'M20F',
 nan,
 'PA-18',
 '206B',
 '150',
 '12',
 '172RG',
 'P210N',
 '170',
 'PA-32-300',
 'B35',
 'PA-36',
 '172',
 '152',
 '310K',
 'M20E',
 'PA-30',
 '600',
 '182L',
 'C-24R',
 'P337H',
 'B58',
 '152',
 'SGS-1-35',
 'PA-38-112',
 'PA-23',
 'AX-7',
 '172',
 '182P',
 'M20K',
 'BC12-D',
 '150',
 '172N',
 '310',
 'PA-28-180',
 '182',
 '114',
 '172M',
 'M20J',
 '172RG',
 'DGA-15P',
 '172M',
 '177RG',
 '206B III',
 'UH-12E',
 'T188C',
 '707-131B',
 'PA-28-140',
 'PA-28R-180',
 'TR182',
 'RS-15',
 '150',
 'PA-28-181',
 'E18S',
 'PA-23 250',
 'SA-266TC',
 'PA-28-181',
 '172',
 'V35B',
 '12E',
 'S-2R',
 '210D',
 'DC-9-82',
 '172',
 'S-2R',
 '2150A',
 'PA-28-151',
 '150M',
 'CB-1',
 'U-206',
 '180',
 '7GCBC',
 '262A-12',
 'T337C',
 '150J',
 '95-55',
 '95-B55',
 '172',
 '172G',
 '310',
 'R22',
 'PA-38-112',
 'PA-28-181',
 'PA-34-200',
 'F33A',
 'PA-30',
 '182',
 '501',
 '7ECA',
 '182J',
 '172',
 'A36TC',
 'PA-32',
 'M-1',
 '172',
 '210G',
 '120',
 'AA-1',
 'KC-135A',
 'PA-22-150',
 'PA-32-301T',
 '182B',
 'H-295',
 '182H',
 '152',
 'C-1',
 '182',
 '182',
 '200',
 'PA-28',
 '172N',
 'BC12-D',
 '182',
 'PA-28R-201',
 'C-45H',
 'T188C',
 'PA-18-135',
 '210',
 '210M',
 'B24R',
 '152',
 '182P',
 'T210G',
 '172',
 'G-164B',
 'PA-31P',
 '182',
 '185',
 '58',
 '340A',
 '402C',
 '340',
 'T210M',
 'C24R',
 '206B',
 '206 L-1',
 '172N',
 'M20K',
 'PA-18-150',
 '172N',
 '150',
 'PA-28RT-201',
 '152',
 'PA-38-112',
 'UH12E',
 '182',
 'J3C-65',
 '401',
 'PA-24-260',
 '421',
 'BD-4',
 'M20F',
 'PA-28-161',
 '180J',
 'PA-24-250',
 'A188B',
 '47J-2A',
 'F35',
 '182',
 '421C',
 'B-8M',
 '177',
 'PA-38',
 'NA-265-80',
 '172F',
 '172N',
 '172N',
 '8E',
 'A23-24',
 '8E',
 '150',
 'F-28A',
 'P-2 BIPLANE',
 'HP-10',
 '210',
 'H-369HS',
 'M20E',
 '152',
 'U206G',
 'T210M',
 'PA-32R',
 '150',
 'R-22',
 'AA-5B',
 '172M',
 'PHOEBUS C',
 '172',
 '150M',
 'SA316B',
 '172',
 'DGA-15P',
 '152',
 '310B',
 '177',
 'AT-301',
 '414',
 'PA-38',
 'PA-28-140',
 '8KCAB',
 'PA-38-112',
 '172',
 '690A',
 'BC-12D',
 '65-A90',
 '150',
 'PA-28-140',
 'PA-44',
 'AC-100',
 'PA-30',
 '707-123B',
 'PA-28-201T',
 '150',
 'PA-28-236',
 '152',
 'SCORPION TOO',
 'PA-28-151',
 'G159-C',
 '65-88',
 'PA-28R-180',
 '150L',
 '150L',
 '177RG',
 'PA-38-112',
 '152',
 'T182RG',
 '58',
 '206',
 '58',
 'M20F',
 '152',
 '182',
 'PA-28-235',
 '7GCBC',
 '310Q',
 '108-2',
 '175',
 '150F',
 'RF4D',
 '25',
 '95-B55',
 'T210N',
 '310D',
 'PA-28-140',
 '150G',
 'PA-28-180',
 'PA-11',
 'PA-32-301T',
 'C-46A',
 'M2OJ',
 '690C',
 '150H',
 'PA-32R',
 '415-C',
 '182K',
 '100',
 '180',
 'PA-24-250',
 'B35',
 '180K',
 'SA226TC',
 '152',
 '172L',
 '172K',
 'PA-32-300',
 'A188B',
 'PA-32R',
 'A185E',
 'PA-28R-200',
 '172',
 '206-F',
 '180',
 'PA-28-140',
 'PA-31-350',
 '172',
 'PA-31-350',
 'BO-105CBS',
 'M35',
 'SABRELINER 65',
 'PA-31P',
 '182',
 'UH-12E',
 '205',
 'PA-36',
 '210N',
 'PA-18',
 'D55',
 '7-B',
 'A36',
 '150M',
 '150',
 'C23',
 'B35',
 'F33A',
 '172N',
 '601P',
 '172',
 '172',
 '182',
 '182RG',
 '150F',
 '402B',
 '95',
 'PA-28-180',
 'PA-31-350',
 'S-2R',
 'PA-44-180',
 '150',
 'PA-28R-201T',
 'SA226TC',
 'T210L',
 'A185E',
 'S-58J',
 'E55',
 'M20B',
 '320F',
 '177RG',
 'NAVION A',
 'PA-24-250',
 '421B',
 'G-164',
 'PA-23-150',
 '310',
 '340A',
 '180K',
 '152',
 '65-A90',
 'AT-400',
 'PA-28-181',
 'PA-28R-201',
 '150',
 'C-18S',
 '172',
 'PA-32',
 'PA-25-235',
 '177',
 '3/4 SPITFIRE',
 '727-200',
 '47G-2A',
 '11AC',
 '152',
 '210A',
 'PA-23-170',
 '206',
 '182M',
 'PA-28-181',
 'PA-38-112',
 'R-22',
 '150',
 '172',
 'PA-28-140',
 'A152',
 '172N',
 '182',
 '369D',
 '47G-4',
 'S1S',
 'PA-23-250',
 '172',
 '172P',
 'PA-22-160',
 'F-19',
 'PA-32',
 'AEROSTAR 602P',
 '180',
 '172',
 'AS350D ASTAR',
 '269B',
 'G-164A',
 '150G',
 'M20F',
 'PA-34',
 '206B',
 '108-1',
 '177',
 'FGID(F4U)',
 nan,
 'K.R.1',
 '170A',
 'UH-12E',
 '47G-2',
 'PA-32R-300',
 'PA-28-235',
 '172N',
 'VARIEZE',
 'SPEED ASTIR II',
 'ASW-20',
 'AA-5B',
 '205',
 '182A',
 '170B',
 'PA-31',
 'PA-25-235D',
 'SA 318C',
 'SA315B',
 '222',
 'M20J',
 '210-5',
 'M-4-220C',
 '77',
 '182G',
 'S-2R',
 'AA-5B',
 'PA-23',
 'PA-34-200J',
 'VP2',
 '172N',
 '150',
 '1-126E',
 '369HS',
 '210D',
 'R-22',
 'S2R-600',
 'B-19',
 '8A',
 'PA-28R-200',
 '172M',
 'M-5-210C',
 'SGS-2-33A',
 '150',
 'B19',
 '201C',
 'MINIPLANE DSA-1',
 '150',
 '172',
 'SV4B',
 'PA-31-350',
 '182P',
 'S-35',
 '411',
 'RX-6',
 'BE-99',
 'PT-19',
 '152',
 '177',
 'DH-82A',
 'VP-1',
 '150',
 'PA-28-140',
 '172',
 '172N',
 'C23-180',
 '727-200',
 '177RG',
 '172',
 'PA-28-140',
 '500C',
 'NA-265-65',
 '152',
 'L-1011',
 '150K',
 'SA315B',
 'PA-32',
 'MU-2B-30',
 'PA-38-112',
 'M-4',
 'A150M',
 'B95',
 'A36TC',
 'PA-28-140',
 'S-1C',
 'H-19A',
 'R-22',
 '269A',
 '320A',
 '201B',
 'PA-38-112',
 '212',
 '172D',
 '152',
 'J5A',
 'A-M-1',
 'PA-18-180',
 '150',
 '172',
 '206L-1',
 '12E',
 'G-164',
 'M20K',
 '210',
 'S-2A',
 'SNJ-2',
 'PA-28-140',
 'A60',
 '7ECA',
 'PA-18-150',
 '182P',
 '150',
 'PA-38-112',
 '23',
 '150',
 'AS350',
 'SKYHAWK',
 '7ECA',
 '201A',
 '150',
 '152',
 'PA-38-112',
 '77',
 'BE-23',
 'KR-II',
 'SPORT DAL-1',
 '206L',
 '8F',
 'ASW-19',
 'KR-1 CATFISH',
 'D52',
 '421C',
 'G-164A',
 'MUSTANG II',
 '95-B55',
 '172N',
 '300A',
 'A36TC',
 'J3C-65',
 '172',
 '150M',
 '8A',
 '182',
 'PA-23',
 '172E',
 '170',
 '206L',
 '8KCAB',
 '206A',
 'PA-44-180',
 'AS-350D',
 '280-C',
 '90',
 'BO-105C',
 'A75',
 'B23',
 '152',
 '47G-3B',
 '601P',
 'PA-23-250T',
 'PA-22-150',
 '440A',
 '369D (500D)',
 '411A',
 'E18S',
 ...]

In [7]:
df['Location'].fillna(value=df['Location'].mode()[0], inplace=True)

In [16]:
# df.isna().sum()
df.tail()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,...,Engine.Type,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
88884,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,Minor,Substantial,...,Reciprocating,Personal,0.0,1.0,0.0,0.0,VMC,NaN,Probable Cause,29-12-2022
88885,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,Non-Fatal,Substantial,...,Reciprocating,Personal,0.0,0.0,0.0,0.0,VMC,NaN,Probable Cause,NaN
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,PAN,PAYSON,Non-Fatal,Substantial,...,Reciprocating,Personal,0.0,0.0,0.0,1.0,VMC,NaN,Probable Cause,27-12-2022
88887,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,Non-Fatal,Substantial,...,Reciprocating,Personal,0.0,0.0,0.0,0.0,VMC,NaN,Probable Cause,NaN
88888,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,Minor,Substantial,...,Reciprocating,Personal,0.0,1.0,0.0,1.0,VMC,NaN,Probable Cause,30-12-2022

In [9]:
df['Country'].fillna(value=df['Country'].mode()[0], inplace=True)
df['Injury.Severity'].fillna(value=df['Injury.Severity'].mode()[0], inplace=True)
df['Aircraft.damage'].fillna(value=df['Aircraft.damage'].mode()[0], inplace=True)
df['Registration.Number'].fillna(value=df['Registration.Number'].mode()[0], inplace=True)
df['Make'].fillna(value=df['Make'].mode()[0], inplace=True)
df['Model'].fillna(value=df['Model'].mode()[0], inplace=True)
df['Amateur.Built'].fillna(value=df['Amateur.Built'].mode()[0], inplace=True)
df['Number.of.Engines'].fillna(value=df['Number.of.Engines'].mode()[0], inplace=True)
df['Engine.Type'].fillna(value=df['Engine.Type'].mode()[0], inplace=True)
df['Purpose.of.flight'].fillna(value=df['Purpose.of.flight'].mode()[0], inplace=True)
df['Weather.Condition'].fillna(value=df['Weather.Condition'].mode()[0], inplace=True)
df['Report.Status'].fillna(value=df['Report.Status'].mode()[0], inplace=True)
df['Total.Uninjured'].fillna(value=df['Total.Uninjured'].mode()[0], inplace=True)

In [10]:
df.isna().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                      0
Country                       0
Latitude                  54507
Longitude                 54516
Airport.Code              38640
Airport.Name              36099
Injury.Severity               0
Aircraft.damage               0
Aircraft.Category         56602
Registration.Number           0
Make                          0
Model                         0
Amateur.Built                 0
Number.of.Engines             0
Engine.Type                   0
FAR.Description           56866
Schedule                  76307
Purpose.of.flight             0
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured               0
Weather.Condition             0
Broad.phase.of.flight     27165
Report.Status                 0
Publication.Date          13771
dtype: int64

In [11]:
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,0.0,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [12]:
df = df.dropna(thresh = 50000, axis = 1)

In [13]:
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,...,Engine.Type,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,Fatal(2),Destroyed,...,Reciprocating,Personal,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,Fatal(4),Destroyed,...,Reciprocating,Personal,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,NaN,NaN,Fatal(3),Destroyed,...,Reciprocating,Personal,3.0,NaN,NaN,0.0,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,Fatal(2),Destroyed,...,Reciprocating,Personal,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,Fatal(1),Destroyed,...,Reciprocating,Personal,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [14]:
df.isna().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                      0
Country                       0
Airport.Code              38640
Airport.Name              36099
Injury.Severity               0
Aircraft.damage               0
Registration.Number           0
Make                          0
Model                         0
Amateur.Built                 0
Number.of.Engines             0
Engine.Type                   0
Purpose.of.flight             0
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured               0
Weather.Condition             0
Broad.phase.of.flight     27165
Report.Status                 0
Publication.Date          13771
dtype: int64

In [15]:
df['Airport.Code','Airport.Name','Broad.phase.of.flight'].fillna('Unknown', inplace = True)

KeyError: ('Airport.Code', 'Airport.Name', 'Broad.phase.of.flight')

In [ ]:
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,...,Engine.Type,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,Unknown,NaN,Fatal(2),Destroyed,...,Reciprocating,Personal,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,Unknown,NaN,Fatal(4),Destroyed,...,Reciprocating,Personal,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,Unknown,NaN,Fatal(3),Destroyed,...,Reciprocating,Personal,3.0,NaN,NaN,0.0,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,Unknown,NaN,Fatal(2),Destroyed,...,Reciprocating,Personal,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,Unknown,NaN,Fatal(1),Destroyed,...,Reciprocating,Personal,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [ ]:
df.isna().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                      0
Country                       0
Airport.Code                  0
Airport.Name              36099
Injury.Severity               0
Aircraft.damage               0
Registration.Number           0
Make                          0
Model                         0
Amateur.Built                 0
Number.of.Engines             0
Engine.Type                   0
Purpose.of.flight             0
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured               0
Weather.Condition             0
Broad.phase.of.flight     27165
Report.Status                 0
Publication.Date          13771
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88889 non-null  object
 5   Country                 88889 non-null  object
 6   Airport.Code            50249 non-null  object
 7   Airport.Name            52790 non-null  object
 8   Injury.Severity         88889 non-null  object
 9   Aircraft.damage         88889 non-null  object
 10  Registration.Number     88889 non-null  object
 11  Make                    88889 non-null  object
 12  Model                   88889 non-null  object
 13  Amateur.Built           88889 non-null  object
 14  Number.of.Engines       88889 non-null  float64
 15  Engine.Type             88889 non-null  object
 16  Purpose.of.flight       88889 non-null  object
 17  Total.Fatal.Injuries    77488 non-null  float64
 18  Total.Serious.Injuries  76379 non-null  float64
 19  Total.Minor.Injuries    76956 non-null  float64
 20  Total.Uninjured         88889 non-null  float64
 21  Weather.Condition       88889 non-null  object
 22  Broad.phase.of.flight   61724 non-null  object
 23  Report.Status           88889 non-null  object
 24  Publication.Date        75118 non-null  object
dtypes: float64(5), object(20)
memory usage: 17.0+ MB