# Series
## A Series is a one-dimensional labelled array that holds any type of data (integers, strings, floats, etc)

In [1]:
import pandas as pd

# Pandas Series
nums = pd.Series([10, 20, 30, 40])
nums

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
temps = pd.Series(
    [18, 23, 27, 20], 
    index = ['Monday', 'Tuesday', 'Wednesday', 'Thursday'])

temps

Monday       18
Tuesday      23
Wednesday    27
Thursday     20
dtype: int64

# DataFrame
## A DataFrame is a two-dimensional table (like an Excel sheet) that consists of rows and columns. It's essentially a collection of multiple Series.

In [3]:
# Pandas DataFrame
data = {
    'Name': ['Francis', 'Githaiga', 'Olin'],
    'Age': [25, 23, 21],
    'County': ['Nairobi', 'Kiambu', 'Nyeri']
}

df = pd.DataFrame(data)
df

       Name  Age   County
0   Francis   25  Nairobi
1  Githaiga   23   Kiambu
2      Olin   21    Nyeri

In [5]:
#set your own IDs
# Pandas DataFrame
data = {
    'Name': ['Francis', 'Githaiga', 'Olin'],
    'Age': [25, 23, 21],
    'County': ['Nairobi', 'Kiambu', "Murang'a"]
}

ids = [101, 102, 103]
df = pd.DataFrame(data , index = ids)
df

         Name  Age    County
101   Francis   25   Nairobi
102  Githaiga   23    Kiambu
103      Olin   21  Murang'a

# CSV DictReader
### Used to convert all details to dictionary

In [10]:
import csv
with open("./results.csv") as f:
    reader = csv.DictReader(f)
    olympics_data = list(reader)

In [11]:
    
#Print the first five rows
for index in range(5):
    #range(5) == range(0, 5) == 0, 1, 2, 3, 4
    print(olympics_data[index])

{'Gender': 'M', 'Event': '10000M Men', 'Location': 'Rio', 'Year': '2016', 'Medal': 'G', 'Name': 'Mohamed FARAH', 'Nationality': 'USA', 'Result': '25:05.17'}
{'Gender': 'M', 'Event': '10000M Men', 'Location': 'Rio', 'Year': '2016', 'Medal': 'S', 'Name': 'Paul Kipngetich TANUI', 'Nationality': 'KEN', 'Result': '27:05.64'}
{'Gender': 'M', 'Event': '10000M Men', 'Location': 'Rio', 'Year': '2016', 'Medal': 'B', 'Name': 'Tamirat TOLA', 'Nationality': 'ETH', 'Result': '27:06.26'}
{'Gender': 'M', 'Event': '10000M Men', 'Location': 'Beijing', 'Year': '2008', 'Medal': 'G', 'Name': 'Kenenisa BEKELE', 'Nationality': 'ETH', 'Result': '27:01.17'}
{'Gender': 'M', 'Event': '10000M Men', 'Location': 'Beijing', 'Year': '2008', 'Medal': 'S', 'Name': 'Sileshi SIHINE', 'Nationality': 'ETH', 'Result': '27:02.77'}

In [13]:
olympics_data

[{'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Rio',
  'Year': '2016',
  'Medal': 'G',
  'Name': 'Mohamed FARAH',
  'Nationality': 'USA',
  'Result': '25:05.17'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Rio',
  'Year': '2016',
  'Medal': 'S',
  'Name': 'Paul Kipngetich TANUI',
  'Nationality': 'KEN',
  'Result': '27:05.64'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Rio',
  'Year': '2016',
  'Medal': 'B',
  'Name': 'Tamirat TOLA',
  'Nationality': 'ETH',
  'Result': '27:06.26'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Beijing',
  'Year': '2008',
  'Medal': 'G',
  'Name': 'Kenenisa BEKELE',
  'Nationality': 'ETH',
  'Result': '27:01.17'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Beijing',
  'Year': '2008',
  'Medal': 'S',
  'Name': 'Sileshi SIHINE',
  'Nationality': 'ETH',
  'Result': '27:02.77'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Beijing',
  'Year': '2008',
  'Medal': 'B',
  'Name': 'Micah KOGO',
  'Nationality': 'KEN',
  'Result': '27:04.11'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Sydney',
  'Year': '2000',
  'Medal': 'G',
  'Name': 'Haile GEBRSELASSIE',
  'Nationality': 'ETH',
  'Result': '27:18.20'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Sydney',
  'Year': '2000',
  'Medal': 'S',
  'Name': 'Paul TERGAT',
  'Nationality': 'KEN',
  'Result': '27:18.29'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Sydney',
  'Year': '2000',
  'Medal': 'B',
  'Name': 'Assefa MEZGEBU',
  'Nationality': 'ETH',
  'Result': '27:19.75'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Barcelona',
  'Year': '1992',
  'Medal': 'G',
  'Name': 'Khalid SKAH',
  'Nationality': 'MAR',
  'Result': '27:46.70'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Barcelona',
  'Year': '1992',
  'Medal': 'S',
  'Name': 'Richard CHELIMO',
  'Nationality': 'KEN',
  'Result': '27:47.72'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Barcelona',
  'Year': '1992',
  'Medal': 'B',
  'Name': 'Addis ABEBE',
  'Nationality': 'ETH',
  'Result': '28:00.07'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Los Angeles',
  'Year': '1984',
  'Medal': 'G',
  'Name': 'Alberto COVA',
  'Nationality': 'ITA',
  'Result': '27:47.54'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Los Angeles',
  'Year': '1984',
  'Medal': 'S',
  'Name': 'Michael MCLEOD',
  'Nationality': 'GBR',
  'Result': '28:06.22'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Los Angeles',
  'Year': '1984',
  'Medal': 'B',
  'Name': 'Michael MUSYOKI',
  'Nationality': 'KEN',
  'Result': '28:06.46'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Montreal',
  'Year': '1976',
  'Medal': 'G',
  'Name': 'Lasse VIREN',
  'Nationality': 'FIN',
  'Result': '27:40.38'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Montreal',
  'Year': '1976',
  'Medal': 'S',
  'Name': 'Carlos LOPES',
  'Nationality': 'POR',
  'Result': '27:45.17'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Montreal',
  'Year': '1976',
  'Medal': 'B',
  'Name': 'Brendan FOSTER',
  'Nationality': 'GBR',
  'Result': '27:54.92'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Mexico',
  'Year': '1968',
  'Medal': 'G',
  'Name': 'Naftali TEMU',
  'Nationality': 'KEN',
  'Result': '29:27.4'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Mexico',
  'Year': '1968',
  'Medal': 'S',
  'Name': 'Mamo WOLDE',
  'Nationality': 'ETH',
  'Result': '29:28.0'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Mexico',
  'Year': '1968',
  'Medal': 'B',
  'Name': 'Mohamed GAMMOUDI',
  'Nationality': 'TUN',
  'Result': '29:34.2'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Rome',
  'Year': '1960',
  'Medal': 'G',
  'Name': 'Pyotr BOLOTNIKOV',
  'Nationality': 'URS',
  'Result': '28:32.2'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Rome',
  'Year': '1960',
  'Medal': 'S',
  'Name': 'Hans GRODOTZKI',
  'Nationality': 'EUA',
  'Result': '28:37.0'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Rome',
  'Year': '1960',
  'Medal': 'B',
  'Name': 'David POWER',
  'Nationality': 'AUS',
  'Result': '28:38.2'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Helsinki',
  'Year': '1952',
  'Medal': 'G',
  'Name': 'Emil ZÃ\x81TOPEK',
  'Nationality': 'TCH',
  'Result': '29:17.0'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Helsinki',
  'Year': '1952',
  'Medal': 'S',
  'Name': 'Alain MIMOUN',
  'Nationality': 'FRA',
  'Result': '29:32.8'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Helsinki',
  'Year': '1952',
  'Medal': 'B',
  'Name': 'Aleksandr ANUFRIYEV',
  'Nationality': 'URS',
  'Result': '29:48.2'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Berlin',
  'Year': '1936',
  'Medal': 'G',
  'Name': 'Ilmari SALMINEN',
  'Nationality': 'FIN',
  'Result': '30:15.4'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Berlin',
  'Year': '1936',
  'Medal': 'S',
  'Name': 'Arvo ASKOLA',
  'Nationality': 'FIN',
  'Result': '30:15.6'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Berlin',
  'Year': '1936',
  'Medal': 'B',
  'Name': 'Volmari ISO-HOLLO',
  'Nationality': 'FIN',
  'Result': '30:20.2'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Amsterdam',
  'Year': '1928',
  'Medal': 'G',
  'Name': 'Paavo NURMI',
  'Nationality': 'FIN',
  'Result': '30:18.8'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Amsterdam',
  'Year': '1928',
  'Medal': 'S',
  'Name': 'Ville RITOLA',
  'Nationality': 'FIN',
  'Result': '30:19.4'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Amsterdam',
  'Year': '1928',
  'Medal': 'B',
  'Name': 'Edvin WIDE',
  'Nationality': 'SWE',
  'Result': '31:00.8'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Antwerp',
  'Year': '1920',
  'Medal': 'G',
  'Name': 'Paavo NURMI',
  'Nationality': 'FIN',
  'Result': '31:45.8'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Antwerp',
  'Year': '1920',
  'Medal': 'S',
  'Name': 'Joseph GUILLEMOT',
  'Nationality': 'FRA',
  'Result': '31:47.2'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Antwerp',
  'Year': '1920',
  'Medal': 'B',
  'Name': 'James WILSON',
  'Nationality': 'GBR',
  'Result': '31:50.8'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'London',
  'Year': '2012',
  'Medal': 'G',
  'Name': 'Mohamed FARAH',
  'Nationality': 'GBR',
  'Result': '27:30.42'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'London',
  'Year': '2012',
  'Medal': 'S',
  'Name': 'Galen RUPP',
  'Nationality': 'USA',
  'Result': '27:30.90'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'London',
  'Year': '2012',
  'Medal': 'B',
  'Name': 'Tariku BEKELE',
  'Nationality': 'ETH',
  'Result': '27:31.43'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Athens',
  'Year': '2004',
  'Medal': 'G',
  'Name': 'Kenenisa BEKELE',
  'Nationality': 'ETH',
  'Result': '27:05.10'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Athens',
  'Year': '2004',
  'Medal': 'S',
  'Name': 'Sileshi SIHINE',
  'Nationality': 'ETH',
  'Result': '27:09.39'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Athens',
  'Year': '2004',
  'Medal': 'B',
  'Name': 'Zersenay TADESE',
  'Nationality': 'ERI',
  'Result': '27:22.57'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Atlanta',
  'Year': '1996',
  'Medal': 'G',
  'Name': 'Haile GEBRSELASSIE',
  'Nationality': 'ETH',
  'Result': '27:07.34'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Atlanta',
  'Year': '1996',
  'Medal': 'S',
  'Name': 'Paul TERGAT',
  'Nationality': 'KEN',
  'Result': '27:08.17'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Atlanta',
  'Year': '1996',
  'Medal': 'B',
  'Name': 'Salah HISSOU',
  'Nationality': 'MAR',
  'Result': '27:24.67'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Moscow',
  'Year': '1980',
  'Medal': 'G',
  'Name': 'Miruts YIFTER',
  'Nationality': 'ETH',
  'Result': '27:42.7'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Moscow',
  'Year': '1980',
  'Medal': 'S',
  'Name': 'Kaarlo MAANINKA',
  'Nationality': 'FIN',
  'Result': '27:44.3'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Moscow',
  'Year': '1980',
  'Medal': 'B',
  'Name': 'Mohammed KEDIR',
  'Nationality': 'ETH',
  'Result': '27:44.7'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Munich',
  'Year': '1972',
  'Medal': 'G',
  'Name': 'Lasse VIREN',
  'Nationality': 'FIN',
  'Result': '27:38.35'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Munich',
  'Year': '1972',
  'Medal': 'S',
  'Name': 'Emiel PUTTEMANS',
  'Nationality': 'BEL',
  'Result': '27:39.58'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Munich',
  'Year': '1972',
  'Medal': 'B',
  'Name': 'Miruts YIFTER',
  'Nationality': 'ETH',
  'Result': '27:40.96'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Tokyo',
  'Year': '1964',
  'Medal': 'G',
  'Name': 'Billy MILLS',
  'Nationality': 'USA',
  'Result': '28:24.4'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Tokyo',
  'Year': '1964',
  'Medal': 'S',
  'Name': 'Mohamed GAMMOUDI',
  'Nationality': 'TUN',
  'Result': '28:24.8'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Tokyo',
  'Year': '1964',
  'Medal': 'B',
  'Name': 'Ron CLARKE',
  'Nationality': 'AUS',
  'Result': '28:25.8'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Melbourne / Stockholm',
  'Year': '1956',
  'Medal': 'G',
  'Name': 'Vladimir KUTS',
  'Nationality': 'URS',
  'Result': '28:45.6'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Melbourne / Stockholm',
  'Year': '1956',
  'Medal': 'S',
  'Name': 'JÃ³zsef KOVÃ\x81CS',
  'Nationality': 'HUN',
  'Result': '28:52.4'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Melbourne / Stockholm',
  'Year': '1956',
  'Medal': 'B',
  'Name': 'Allan LAWRENCE',
  'Nationality': 'AUS',
  'Result': '28:53.6'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'London',
  'Year': '1948',
  'Medal': 'G',
  'Name': 'Emil ZÃ\x81TOPEK',
  'Nationality': 'TCH',
  'Result': '29:59.6'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'London',
  'Year': '1948',
  'Medal': 'S',
  'Name': 'Alain MIMOUN',
  'Nationality': 'FRA',
  'Result': '30:47.4'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'London',
  'Year': '1948',
  'Medal': 'B',
  'Name': 'Bertil ALBERTSSON',
  'Nationality': 'SWE',
  'Result': '30:53.6'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Los Angeles',
  'Year': '1932',
  'Medal': 'G',
  'Name': 'Janusz KUSOCINSKI',
  'Nationality': 'POL',
  'Result': '30:11.4'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Los Angeles',
  'Year': '1932',
  'Medal': 'S',
  'Name': 'Volmari ISO-HOLLO',
  'Nationality': 'FIN',
  'Result': '30:12.6'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Los Angeles',
  'Year': '1932',
  'Medal': 'B',
  'Name': 'Lauri VIRTANEN',
  'Nationality': 'FIN',
  'Result': '30:35.0'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Paris',
  'Year': '1924',
  'Medal': 'G',
  'Name': 'Ville RITOLA',
  'Nationality': 'FIN',
  'Result': '30:23.2'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Paris',
  'Year': '1924',
  'Medal': 'S',
  'Name': 'Edvin WIDE',
  'Nationality': 'SWE',
  'Result': '30:55.2'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Paris',
  'Year': '1924',
  'Medal': 'B',
  'Name': 'Eero BERG',
  'Nationality': 'FIN',
  'Result': '31:43.0'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Stockholm',
  'Year': '1912',
  'Medal': 'G',
  'Name': 'Hannes KOLEHMAINEN',
  'Nationality': 'FIN',
  'Result': '31:20.8'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Stockholm',
  'Year': '1912',
  'Medal': 'S',
  'Name': 'Lewis TEWANIMA',
  'Nationality': 'USA',
  'Result': '32:06.6'},
 {'Gender': 'M',
  'Event': '10000M Men',
  'Location': 'Stockholm',
  'Year': '1912',
  'Medal': 'B',
  'Name': 'Albin STENROOS',
  'Nationality': 'FIN',
  'Result': '32:21.8'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Rio',
  'Year': '2016',
  'Medal': 'G',
  'Name': 'Usain BOLT',
  'Nationality': 'JAM',
  'Result': '9.81'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Rio',
  'Year': '2016',
  'Medal': 'S',
  'Name': 'Justin GATLIN',
  'Nationality': 'USA',
  'Result': '9.89'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Rio',
  'Year': '2016',
  'Medal': 'B',
  'Name': 'Andre DE GRASSE',
  'Nationality': 'CAN',
  'Result': '9.91'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Beijing',
  'Year': '2008',
  'Medal': 'G',
  'Name': 'Usain BOLT',
  'Nationality': 'JAM',
  'Result': '9.69'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Beijing',
  'Year': '2008',
  'Medal': 'S',
  'Name': 'Richard THOMPSON',
  'Nationality': 'TTO',
  'Result': '9.89'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Beijing',
  'Year': '2008',
  'Medal': 'B',
  'Name': 'Walter DIX',
  'Nationality': 'USA',
  'Result': '9.91'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Sydney',
  'Year': '2000',
  'Medal': 'G',
  'Name': 'Maurice GREENE',
  'Nationality': 'USA',
  'Result': '9.87'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Sydney',
  'Year': '2000',
  'Medal': 'S',
  'Name': 'Ato BOLDON',
  'Nationality': 'TTO',
  'Result': '9.99'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Sydney',
  'Year': '2000',
  'Medal': 'B',
  'Name': 'Obadele THOMPSON',
  'Nationality': 'BAR',
  'Result': '10.04'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Barcelona',
  'Year': '1992',
  'Medal': 'G',
  'Name': 'Linford CHRISTIE',
  'Nationality': 'GBR',
  'Result': '9.96'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Barcelona',
  'Year': '1992',
  'Medal': 'S',
  'Name': 'Frank FREDERICKS',
  'Nationality': 'NAM',
  'Result': '10.02'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Barcelona',
  'Year': '1992',
  'Medal': 'B',
  'Name': 'Dennis MITCHELL',
  'Nationality': 'USA',
  'Result': '10.04'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Los Angeles',
  'Year': '1984',
  'Medal': 'G',
  'Name': 'Carl LEWIS',
  'Nationality': 'USA',
  'Result': '9.99'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Los Angeles',
  'Year': '1984',
  'Medal': 'S',
  'Name': 'Sam GRADDY',
  'Nationality': 'USA',
  'Result': '10.19'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Los Angeles',
  'Year': '1984',
  'Medal': 'B',
  'Name': 'Ben JOHNSON',
  'Nationality': 'CAN',
  'Result': '10.22'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Montreal',
  'Year': '1976',
  'Medal': 'G',
  'Name': 'Hasely CRAWFORD',
  'Nationality': 'TTO',
  'Result': '10.06'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Montreal',
  'Year': '1976',
  'Medal': 'S',
  'Name': 'Donald QUARRIE',
  'Nationality': 'JAM',
  'Result': '10.08'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Montreal',
  'Year': '1976',
  'Medal': 'B',
  'Name': 'Valery BORZOV',
  'Nationality': 'URS',
  'Result': '10.14'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Mexico',
  'Year': '1968',
  'Medal': 'G',
  'Name': 'Jim HINES',
  'Nationality': 'USA',
  'Result': '9.9'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Mexico',
  'Year': '1968',
  'Medal': 'S',
  'Name': 'Lennox MILLER',
  'Nationality': 'JAM',
  'Result': '10.0'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Mexico',
  'Year': '1968',
  'Medal': 'B',
  'Name': 'Charlie GREENE',
  'Nationality': 'USA',
  'Result': '10.0'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Rome',
  'Year': '1960',
  'Medal': 'G',
  'Name': 'Armin HARY',
  'Nationality': 'EUA',
  'Result': '10.2'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Rome',
  'Year': '1960',
  'Medal': 'S',
  'Name': 'Dave SIME',
  'Nationality': 'USA',
  'Result': '10.2'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Rome',
  'Year': '1960',
  'Medal': 'B',
  'Name': 'Peter RADFORD',
  'Nationality': 'GBR',
  'Result': '10.3'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Helsinki',
  'Year': '1952',
  'Medal': 'G',
  'Name': 'Lindy REMIGINO',
  'Nationality': 'USA',
  'Result': '10.4'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Helsinki',
  'Year': '1952',
  'Medal': 'S',
  'Name': 'Herbert MCKENLEY',
  'Nationality': 'JAM',
  'Result': '10.4'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Helsinki',
  'Year': '1952',
  'Medal': 'B',
  'Name': 'Emmanuel McDONALD BAILEY',
  'Nationality': 'GBR',
  'Result': '10.4'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Berlin',
  'Year': '1936',
  'Medal': 'G',
  'Name': 'Jesse OWENS',
  'Nationality': 'USA',
  'Result': '10.3'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Berlin',
  'Year': '1936',
  'Medal': 'S',
  'Name': 'Ralph METCALFE',
  'Nationality': 'USA',
  'Result': '10.4'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Berlin',
  'Year': '1936',
  'Medal': 'B',
  'Name': 'Martinus OSENDARP',
  'Nationality': 'NED',
  'Result': '10.5'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Amsterdam',
  'Year': '1928',
  'Medal': 'G',
  'Name': 'Percy WILLIAMS',
  'Nationality': 'CAN',
  'Result': '10.8'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Amsterdam',
  'Year': '1928',
  'Medal': 'S',
  'Name': 'Jack LONDON',
  'Nationality': 'GBR',
  'Result': '10.9'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Amsterdam',
  'Year': '1928',
  'Medal': 'B',
  'Name': 'Georg LAMMERS',
  'Nationality': 'GER',
  'Result': '10.9'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Antwerp',
  'Year': '1920',
  'Medal': 'G',
  'Name': 'Charles PADDOCK',
  'Nationality': 'USA',
  'Result': '10.8'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Antwerp',
  'Year': '1920',
  'Medal': 'S',
  'Name': 'Morris KIRKSEY',
  'Nationality': 'USA',
  'Result': '10.8'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Antwerp',
  'Year': '1920',
  'Medal': 'B',
  'Name': 'Harry EDWARD',
  'Nationality': 'GBR',
  'Result': '10.9'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'London',
  'Year': '1908',
  'Medal': 'G',
  'Name': 'Reggie WALKER',
  'Nationality': 'RSA',
  'Result': '10.8'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'London',
  'Year': '1908',
  'Medal': 'S',
  'Name': 'John RECTOR',
  'Nationality': 'USA',
  'Result': 'None'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'London',
  'Year': '1908',
  'Medal': 'B',
  'Name': 'Robert KERR',
  'Nationality': 'CAN',
  'Result': 'None'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Paris',
  'Year': '1900',
  'Medal': 'G',
  'Name': 'Frank JARVIS',
  'Nationality': 'USA',
  'Result': '11.0'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Paris',
  'Year': '1900',
  'Medal': 'S',
  'Name': 'Walter TEWKSBURY',
  'Nationality': 'USA',
  'Result': '11.1'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'Paris',
  'Year': '1900',
  'Medal': 'B',
  'Name': 'Stanley ROWLEY',
  'Nationality': 'AUS',
  'Result': '11.2'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'London',
  'Year': '2012',
  'Medal': 'G',
  'Name': 'Usain BOLT',
  'Nationality': 'JAM',
  'Result': '9.63'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'London',
  'Year': '2012',
  'Medal': 'S',
  'Name': 'Yohan BLAKE',
  'Nationality': 'JAM',
  'Result': '9.75'},
 {'Gender': 'M',
  'Event': '100M Men',
  'Location': 'London',
  'Year': '2012',
  'Medal': 'B',
  'Name': 'Justin GATLIN',
  'Nationality': 'USA',
  'Result': '9.79'},
 {'Gender': 'M',
  'Event': '100M Men',

In [17]:
olympics_data[2]

{'Gender': 'M',
 'Event': '10000M Men',
 'Location': 'Rio',
 'Year': '2016',
 'Medal': 'B',
 'Name': 'Tamirat TOLA',
 'Nationality': 'ETH',
 'Result': '27:06.26'}

In [20]:
print([row['Location'] for row in olympics_data][:10])

['Rio', 'Rio', 'Rio', 'Beijing', 'Beijing', 'Beijing', 'Sydney', 'Sydney', 'Sydney', 'Barcelona']

In [21]:
import pandas as pd
df = pd.DataFrame(olympics_data)
df

,Gender,Event,Location,Year,Medal,Name,Nationality,Result,NaN
0,M,10000M Men,Rio,2016,G,Mohamed FARAH,USA,25:05.17,NaN
1,M,10000M Men,Rio,2016,S,Paul Kipngetich TANUI,KEN,27:05.64,NaN
2,M,10000M Men,Rio,2016,B,Tamirat TOLA,ETH,27:06.26,NaN
3,M,10000M Men,Beijing,2008,G,Kenenisa BEKELE,ETH,27:01.17,NaN
4,M,10000M Men,Beijing,2008,S,Sileshi SIHINE,ETH,27:02.77,NaN
...,...,...,...,...,...,...,...,...,...
2389,W,Triple Jump Women,Athens,2004,S,Hrysopiyi DEVETZI,GRE,15.25,NaN
2390,W,Triple Jump Women,Athens,2004,B,Tatyana LEBEDEVA,RUS,15.14,NaN
2391,W,Triple Jump Women,Atlanta,1996,G,Inessa KRAVETS,UKR,15.33,NaN
2392,W,Triple Jump Women,Atlanta,1996,S,Inna LASOVSKAYA,RUS,14.98,NaN
2393,W,Triple Jump Women,Atlanta,1996,B,Sarka KASPARKOVA,CZE,14.98,NaN

In [22]:
df.head()

,Gender,Event,Location,Year,Medal,Name,Nationality,Result,NaN
0,M,10000M Men,Rio,2016,G,Mohamed FARAH,USA,25:05.17,NaN
1,M,10000M Men,Rio,2016,S,Paul Kipngetich TANUI,KEN,27:05.64,NaN
2,M,10000M Men,Rio,2016,B,Tamirat TOLA,ETH,27:06.26,NaN
3,M,10000M Men,Beijing,2008,G,Kenenisa BEKELE,ETH,27:01.17,NaN
4,M,10000M Men,Beijing,2008,S,Sileshi SIHINE,ETH,27:02.77,NaN

In [23]:
df.tail()

,Gender,Event,Location,Year,Medal,Name,Nationality,Result,NaN
2389,W,Triple Jump Women,Athens,2004,S,Hrysopiyi DEVETZI,GRE,15.25,NaN
2390,W,Triple Jump Women,Athens,2004,B,Tatyana LEBEDEVA,RUS,15.14,NaN
2391,W,Triple Jump Women,Atlanta,1996,G,Inessa KRAVETS,UKR,15.33,NaN
2392,W,Triple Jump Women,Atlanta,1996,S,Inna LASOVSKAYA,RUS,14.98,NaN
2393,W,Triple Jump Women,Atlanta,1996,B,Sarka KASPARKOVA,CZE,14.98,NaN

In [24]:
df2=pd.read_csv('./results.csv')

ParserError: Error tokenizing data. C error: Expected 8 fields in line 156, saw 9

In [33]:
df2 = pd.read_csv('./results.csv', error_bad_lines=False)
df2.head()

b'Skipping line 156: expected 8 fields, saw 9\nSkipping line 157: expected 8 fields, saw 9\nSkipping line 158: expected 8 fields, saw 9\nSkipping line 317: expected 8 fields, saw 9\nSkipping line 318: expected 8 fields, saw 9\nSkipping line 319: expected 8 fields, saw 9\nSkipping line 1658: expected 8 fields, saw 9\nSkipping line 1659: expected 8 fields, saw 9\nSkipping line 1660: expected 8 fields, saw 9\nSkipping line 1784: expected 8 fields, saw 9\nSkipping line 1785: expected 8 fields, saw 9\nSkipping line 1786: expected 8 fields, saw 9\n'

,Gender,Event,Location,Year,Medal,Name,Nationality,Result
0,M,10000M Men,Rio,2016,G,Mohamed FARAH,USA,25:05.17
1,M,10000M Men,Rio,2016,S,Paul Kipngetich TANUI,KEN,27:05.64
2,M,10000M Men,Rio,2016,B,Tamirat TOLA,ETH,27:06.26
3,M,10000M Men,Beijing,2008,G,Kenenisa BEKELE,ETH,27:01.17
4,M,10000M Men,Beijing,2008,S,Sileshi SIHINE,ETH,27:02.77

In [38]:
df['Location']

0           Rio
1           Rio
2           Rio
3       Beijing
4       Beijing
         ...
2389     Athens
2390     Athens
2391    Atlanta
2392    Atlanta
2393    Atlanta
Name: Location, Length: 2394, dtype: object

In [35]:
df.index

RangeIndex(start=0, stop=2394, step=1)

In [36]:
df.shape

(2394, 9)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2394 entries, 0 to 2393
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Gender       2394 non-null   object
 1   Event        2394 non-null   object
 2   Location     2394 non-null   object
 3   Year         2394 non-null   object
 4   Medal        2394 non-null   object
 5   Name         2394 non-null   object
 6   Nationality  2394 non-null   object
 7   Result       2394 non-null   object
 8   None         12 non-null     object
dtypes: object(9)
memory usage: 168.5+ KB

In [39]:
len(df)

2394

In [40]:
df.columns

Index([     'Gender',       'Event',    'Location',        'Year',
             'Medal',        'Name', 'Nationality',      'Result',
                None],
      dtype='object')

In [41]:
df.dtypes

Gender         object
Event          object
Location       object
Year           object
Medal          object
Name           object
Nationality    object
Result         object
NaN            object
dtype: object

# Selecting DataFrame Information
## Two main methods are used to do the above
### .iloc  and  .loc

....................................................................................................................................................................................................................................................

## .iloc
### Index-Based Selection: Allows selection of data in a dataframe based on integer positions (row & column numbers)

In [43]:
df.iloc[3]

Gender                       M
Event               10000M Men
Location               Beijing
Year                      2008
Medal                        G
Name           Kenenisa BEKELE
Nationality                ETH
Result                27:01.17
NaN                        NaN
Name: 3, dtype: object

In [46]:
#To select several rows
df.iloc[5:10]

,Gender,Event,Location,Year,Medal,Name,Nationality,Result,NaN
5,M,10000M Men,Beijing,2008,B,Micah KOGO,KEN,27:04.11,NaN
6,M,10000M Men,Sydney,2000,G,Haile GEBRSELASSIE,ETH,27:18.20,NaN
7,M,10000M Men,Sydney,2000,S,Paul TERGAT,KEN,27:18.29,NaN
8,M,10000M Men,Sydney,2000,B,Assefa MEZGEBU,ETH,27:19.75,NaN
9,M,10000M Men,Barcelona,1992,G,Khalid SKAH,MAR,27:46.70,NaN

In [47]:
df[5:10]

,Gender,Event,Location,Year,Medal,Name,Nationality,Result,NaN
5,M,10000M Men,Beijing,2008,B,Micah KOGO,KEN,27:04.11,NaN
6,M,10000M Men,Sydney,2000,G,Haile GEBRSELASSIE,ETH,27:18.20,NaN
7,M,10000M Men,Sydney,2000,S,Paul TERGAT,KEN,27:18.29,NaN
8,M,10000M Men,Sydney,2000,B,Assefa MEZGEBU,ETH,27:19.75,NaN
9,M,10000M Men,Barcelona,1992,G,Khalid SKAH,MAR,27:46.70,NaN

In [49]:
df.iloc[:, 3:4]

      Year
0     2016
1     2016
2     2016
3     2008
4     2008
...    ...
2389  2004
2390  2004
2391  1996
2392  1996
2393  1996

[2394 rows x 1 columns]

In [50]:
df.loc[:, 'Medal']
df.loc[3:7, 'Nationality']

3    ETH
4    ETH
5    KEN
6    ETH
7    KEN
Name: Nationality, dtype: object